language: java
jdk: openjdk8
install: true
os: linux
dist: trusty

jobs:
  include:
    - stage: Compilation
      script: ./gradlew classes
  
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
